### PR TITLE
Feature: Recent transactions component

### PR DESCRIPTION
**Pull request by OliwierOST**
Resolves: #111 

Feature: add recent transactions component

image

### CODE REVIEW

**Review by piotrostr — APPROVED** [review]

**Comment by piotrostr** [comment]
lgtm, what would happen if there was a larger amount, like 40k? or 100k? would it still fit in the component without breaking the layout?

**Comment by OliwierOST** [comment]
> lgtm, what would happen if there was a larger amount, like 40k? or 100k? would it still fit in the component without breaking the layout?

The amount of transactions displayed is limited by limit function given by firestore so no need to worry about that.

**Comment by piotrostr** [comment]
> > lgtm, what would happen if there was a larger amount, like 40k? or 100k? would it still fit in the component without breaking the layout?
> 
> The amount of transactions displayed is limited by limit function given by firestore so no need to worry about that.

I mean like $40,000 or $100,000 hahah

**Comment by OliwierOST** [comment]
> > > lgtm, what would happen if there was a larger amount, like 40k? or 100k? would it still fit in the component without breaking the layout?
> > 
> > 
> > The amount of transactions displayed is limited by limit function given by firestore so no need to worry about that.
> 
> I mean like $40,000 or $100,000 hahah

It actually works fine up to 10 million, I don't expect any transactions that are bigger to be made so it should be alright

**Pull request merged**
