### PR TITLE
Feature: reusable course card

### PR DESCRIPTION
**Pull request by JakubFrackowiak**
Resolves: #99

### CODE REVIEW

**Review by OliwierOST — COMMENTED** [review]
lgtm!

**Comment by piotrostr** [comment]
This is legally incorrect @yoniaibi, you cannot mention other websites without their permissions I think

Please provide me some more context around that, for now closing this as out of scope

**Comment by JakubFrackowiak** [comment]
Instead of doing verified course card  I made course card that has isVerified property that changes the course provider to company/course creator , so maybe this code is still usable. 
@piotrostr  @yoniaibi

**Comment by yoniaibi** [comment]
@piotrostr Apologies for the confusion, this verified course tab will only have courses that we have been paid to upload and will only be posted with the sites permission. It will begin as blank but grow as we gain more notoriety which is why we have the free courses for the beginning as well. 
Legally speaking there is also no issue with us recommending what courses we think are good for a freelancer to use as we aren't claimnig it is our course but just telling freelancers what courses we value and will give them XP if they show us proof of completion.

**Comment by piotrostr** [comment]
Okay, under those assumptions and those assumptions only I will re-open

I understand this is a part of MVP and a feature that would be only coming to play a lot further down the road

Will have a look at the PR during the weekend

**Comment by piotrostr** [comment]
> lgtm!

lmao

**Comment by piotrostr** [comment]
text should be white here

**Comment by yoniaibi** [comment]
@piotrostr Amazing that sounds good

**Pull request merged**
